spring:
  application:
    name: dubbo-springboot-demo-provider
  main:
    banner-mode: off
  web:
    resources:
      add-mappings: false
  messages:
    encoding: UTF-8

zk:
  address: zookeeper://192.168.33.20:2181

nacos:
  address: nacos://192.168.33.20:8848

dubbo:
  shutdown:
    hook: true
  service:
    shutdown:
      wait: 40000
  application:
    name: ${spring.application.name}
#    environment: dev
    logger: slf4j
    #provider注册模式，可选值 interface(接口级)、instance(应用级)、all，默认是all(双注册)
    register-mode: all
    metadata-service-port: -1
    #consumer服务发现模式
    service-discovery:
      # FORCE_INTERFACE，只消费接口级地址，如无地址则报错，单订阅 2.x 地址
      # APPLICATION_FIRST，智能决策接口级/应用级地址，双订阅
      # FORCE_APPLICATION，只消费应用级地址，如无地址则报错，单订阅 3.x 地址
      migration: FORCE_APPLICATION
      # 场景: 防止由于类版本不匹配、方法签名不兼容或缺少类而可能发生的潜在问题
      check-serializable: true # 检查序列化接口, 目前序列化检查支持 Hessian2、Fastjson2 序列化以及泛化调用。其他的序列化方式暂不支持
      serialize-check-status: STRICT # 序列化检查方式为严格
      auto-trust-serialize-class: true #  启用扫描
      trust-serialize-class-level: 3
    dump:
      enable: false
      directory: /tmp
    qos-enable: true
    qos-port: 22222
    qos-accept-foreign-ip: true
    qos-accept-foreign-ip-whitelist: 10.0.0.0/8,192.168.0.0/16,172.16.0.0/12
  protocol:
    # 设置为 tri 即可使用 Triple 3.0 新协议
    # 性能对比 dubbo 协议并没有提升 但基于 http2 用于多语言异构等 http 交互场景
    # 使用 dubbo 协议通信
    name: dubbo
    port: -1
    # sent和序列号在io线程上操作
#    dispatcher: all
  registry: # registry的配置会被解析后作为config-center和metadata-report的地址
    id: my-registry
    check: true
    # 推空保护是对消费端而言的，当推空保护开启后，消费端进程会忽略注册中心推送过来的空地址事件（会继续保留当前内存已有地址列表）。
    # 这是避免在一些异常场景下误将注册中心地址列表清空，导致服务调用不可用。
    # 推空保护默认关闭，可通过以下方式开启
    enableEmptyProtection: true
    timeout: 30000 # 连接超时时间，默认 30s
    session: 60000 # 会话超时时间，默认 60s
    # 注册中心缓存文件的默认存放路径是：${HOME}/.dubbo/dubbo-registry-{application-name}-{address}.cache，以一定的间隔定期刷新
    # 如果此时因网络故障等原因导致读取可用地址列表失败，框架会查询本地缓存的注册中心地址并返回（如不想使用使用缓存地址，可通过设置 check=true 快速失败抛出异常）
    file-cache: false
    address: ${zk.address}
#  不想使用 nacos 作为配置中心，可以通过以下两个参数来调整或控制默认行为
#    use-as-config-center: false
#    use-as-metadata-report: false
  config-center:
    address: ${zk.address}
  metadata-report:
    address: ${zk.address}
  consumer:
    timeout: 5000 # 配置客户端超时, 默认1s
    check: false
  metrics:
    protocol: prometheus
    enable-jvm: true
    enable-registry: true
    aggregation:
      enabled: true
    prometheus:
      exporter:
        enabled: true
    enable-metadata: true


logging:
  pattern:
    level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'

server:
  address: 0.0.0.0
  port: 8284
  shutdown: graceful
  servlet:
    encoding:
      charset: UTF-8

management:
  endpoints:
    web:
      exposure:
        # 暴露所有端点
        include: "*"
      # 修改访问路径 默认是/actuator
      base-path: /actuator
  # 显示详细健康信息
  endpoint:
    health:
      show-details: always
